language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - DOCKER_USERNAME=octoblu
  - DEPLOY_APPLICATION_NAME=flow-deploy-service
  - DEPLOY_REGION=us-west-2
  - DEPLOY_BUCKET=octoblu-deploy
  - DEPLOYMENT_GROUP=master
  - DEPLOY_KEY=flow-deploy-service/flow-deploy-service-$TRAVIS_COMMIT.zip
  - FLOW_DEPLOY_SERVICE_UUID=f515e496-c6d5-4195-b3be-6a6fe77b3b51
  - FLEETCTL_ENDPOINT=http://octo-cluster.octoblu.com:4001
  - secure: yL7paMe0ZKjGFiN0AZ8/BYJs8IoeR2t6HP+xU3TEF8ADx/50kQe+sLs/U8MWt0d8ZG9Kz5+ccFyivnO9CRHsPUetRdMLzymaQcYy08qU2sK1TlG6wYvgR19YK/oIyzInUFE7IJESDfckJfqRUxocKV6w/m3SnjBqkescLe0ogSkBiz6zQ+LZIE7egnNZ1wG0g+81/eY8GLsFiujAiwpmVQfYFhDckVgEwPPd93B2BW8wj20Uys5sgQ5RW+mrEvylg0SCVmkQsC/qy1KGBW7OYo3+mAhXY6yVCMO3DrH+0H3vMhO+lWHZ34BhUdgcMbejDjWcwD7maSuI29X/lj1DBCdzFnF5HnkV2kndcYNfezZkW1CSDG9tE4Nk/I1QlDd+cwtUWJIpy3/mJwZqkKNHAOUYDIqlsezyNn1GdLZPmX1UoB2MtC6fZnYrLG4JNKZWiLxRdeu+FQ4/YHAB09PM2K+QXoyb2xR44RNVdmkfCCwAjKbGsK4Zw+8SF3jJIwcVX2ZsTPGWy7G0b9IAt6I59SghwUbJW0zSzVt7HM30lrYrR5x4VxhG4POsBaeI5XowsmH6gIIwad3WyDVmUJ54fxo+XxYDmHonkB4Pxtj++RPdexseEw6JdGO2x5Tbn6V5HZOmTobrtvUm3qSLbUsDgSumL62PYQyI2T78UFOht0Y=
  - secure: okN9STJakwfiymx8K8DW7tu4JoFMHDNJg68jCBzSV+qOBAMGFjPmRlrMDw8EbRYiPoTei44Yiz94lhs0FUik5oZFr1RfA8NscOr/UcfqfQ80Vjm5StQViB4x3QFPkvHpYJkQiEMtJVekxSUtaMjphtz0JHyRpx0LPX6O/oYy9BI+kUBvV5zfstgIpCiYCMOHtNW+Vithe+fmJ2U4g0+UyzU8Nn2IH1lx62mQn4YFGyVvnJmisxhuTNX1gmA8s9GZKgJZz6tUki5tFoglt4NH1FdEP0GcVRbR6fBiPKOwSDatziSobEqlnM+uysiy14pLPDL67ll51L43dxcOErVa7wGfhUPbpTXtshm+Uh5pg3gK99odobHBXG6scpGRgiCJw7MIirn4DoUN2PrpDuMgqWVgrCZ8hrwWJ2Vk+bYDfYWotVZ4F8q+8TumfKJ5fhv0G4qu+cr7NQy5qsebP+2EE/VgPTSsHmuOtOcBzEOHyyJsEnno6o7msWJJfdYEDhaL3wMU4QI4tmO9jyfUNIfx6cLFt5UNeW6rqmEyLj1vVGdeqhYzaJ1YeZj3qwWkQ2SzKKbZOUea09CbngkJmt8Q/WEWccMmNOtzQAUtVVTWj4vcKfTJmZfou0gYQn9//BNxA88IrtuqbzQrOXrteW+e6dX7qS5Px/Qcu2ljAtmwhJY=
  - secure: aXcHUtCL3sYpyIsARX4csDDkkLrnpACKWoPzvo6k4HMKKhX7vipINOGOSNlA/0O9vCQMfFAAcqSTLS+7FhfD04gY1oOYxcS45CPTLdqvBZ/QeKzPg5mat0a0JEZTfS3uSnjzSrCsLe9II8Kf45ElT/7oxFvoMVn6shlAJRl5V/nnanvCs6BtwuD6SXoXxyZNlVDCJxP0vUp26rSUUu2wF/yNIraDjuDYWJj1l/vBctHcV5ZmhVR+yokmp4Eo6CtAt//sDfWCt/kmn4736dB4pLmnuDAubcKdvHyqtVorGFGg2y/0QikpqgUdC6Qer0xUWjCUEuSAwcXSPeQEivFiwluq6tSXR53yG6j+EnRIoDSZU3ML0ccNsV7RJh/LzU9bxOKjMcHDssVsmBPJOnUUJyAAS457mtHXeCmGf6jd/HFX3IXvmwIyc6gDpnHwg4YijGkXzxALAKmBgxu7WuWtOhSf8kcWQMoNg7jVwiNkY3L0nR70up1lEiPHnK23CABdoKB0scfMh9AVuBeEfI4zgzViPMK95EUSQk2IPUmKFB4/wdtGUmOCvoA4NMha89t5kma2biVS1OS9i90QbnUfA0zyquPkCYomN8GdTl3g5iTxRGQwNY82Deh0t9Pp0xp8GFmT11MThz8jaDfh0ftHjlnL9vdwBx+JNaz8jFEWs1Q=
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: bxFzJbLhwL4RKIPNi2feRd46N1z8ION0lsNczCXzXDB5q0dB+myl073k9Nd/wUv2Wsx/YlgScZ2qmQY5vqMM1PFO8eZFgbb8Pilx3FpAwAfG7iME1Ag4+qrvxMNHR77VWQmKzDx3YmLqwRUoh5pKSzFPkvZ7UU75CMXIoUJykh+PuCi/xYPEbNY0K6iwTRC/nPs07dzD2rxJ1imcNE9oOhgsFSS+svVNK8SsZ9rYxJWqWq80yRIU/K40BMWJYzduRwiAvIbGdEIMLWfHZomhm3rB8yJRlMMQhiMIE+WYSOeYShzXRoDG6J4/rcW76JaJitP7Af8kgbPOpXgWGbwOvVGybciq3L/G+44O1t+8PA5cKHvbqNZ2yHN7FbRxaUuwsA/mWPV8o1nffezjeVo3+5MJMo9avQpFTCuRvyiSrjCyf9RPUjIGyIgv71jG3N6iBAC1q0yPa4FFOQfwmZveFDUX564w7Ebazjzu5zkM+M4hmaZrPA+IFS3XEp44c17yZsDlSrTkeqPf69VDEsuKF7smQwbVSx/EELDkdHJMiGt8ynMrBXidZV0DyaW841KSJTCLUunoeJ+NxsJOST+6unVlkbaflEK5Ov0xqW/OJNLFVYw/RjORMPeL8yqrkVhjnKi/XSS6JVpFEZxdsO3hD07sEf5pW5nX2eUUCeejrGU=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: docker-builder/flow-deploy-service-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: docker-builder
  deployment_group: flow-deploy-service
  on:
    branch: master
